config/routes.rb
RubygemsSearch::Application.routes.draw do
  
  # Applications routes
  resources :gems
  
  get "/search" => 'gems#search'
  
  get "/advanced" => 'gems#advanced_search'
  
  root "gems#index"
end

app/models/dependency.rb
class Dependency
  include Mongoid::Document
  
  field :name, type: String
  field :requirements, type: String
  
end

app/models/owner.rb
class Owner
  include Mongoid::Document
  
  field :email, type: String
  field :gittip_username, type: String
  
  embedded_in :ruby_gem
end

app/models/requirement.rb
class Requirement
  include Mongoid::Document
    
  embeds_many :development, store_as: 'development', class_name:'Dependency'
  embeds_many :runtime, store_as: 'runtime', class_name:'Dependency'
  embedded_in :ruby_gem
  
end

app/models/ruby_gem.rb
class RubyGem
  include Mongoid::Document
  
  #### Mongo
  store_in collection: "gems"
  
  field :name, type: String
  field :downloads, type: Integer
  field :version, type: String
  field :version_downloads, type: Integer
  field :platform, type: String
  field :authors, type: String
  field :info, type: String
  field :licenses, type: Array #of strings
  field :project_uri, type: String
  field :gem_uri, type: String
  field :homepage_uri, type: String
  field :wiki_uri, type: String
  field :documentation_uri, type: String
  field :mailing_list_uri, type: String
  field :source_code_uri, type: String
  field :bug_tracker_uri, type: String
  
  embeds_one :dependencies, store_as: 'dependencies', class_name: 'Requirement'
  embeds_many :versions
  embeds_many :owners
  
  index({ name: 1 }, { unique: true, background: true, drop_dups: true })
  
  #### Elastic Search
  include Tire::Model::Search
  include Tire::Model::Callbacks
  
  DEFAULT_SEARCH_SIZE = 25
  
  mapping do
    indexes :id,            index: :not_analyzed
    indexes :name,          type: 'string'
    indexes :original_name, type: 'string', index: :not_analyzed
    indexes :info,          type: 'string'
    indexes :licenses,      type: 'string'  ####
    
    indexes :owners,        type: 'string'
    indexes :authors,       type: 'string'
    indexes :downloads,     type: 'integer'
    
    indexes :runtime_dependencies,  type: 'string' ####
    indexes :dev_dependencies,      type: 'string'
    
    indexes :version,         type: 'string', index: :not_analyzed
    indexes :versions,      type: 'nested', :properties => { 
                                built_at: { :type => 'date' }, 
                                number: { :type => 'string' },
                                description: { type: 'string' },
                                summary: { type: 'string' }
                            }
  end
  
  def to_indexed_json
    { id: id.to_s, 
      name: name, 
      original_name: name,
      info: info, 
      licenses: licenses, 
      downloads: downloads, 
      authors: authors.try(:split, ','), 
      owners:  owners ? owners.map{|o| o.email} : [],
      runtime_dependencies: dependencies && dependencies.runtime ? dependencies.runtime.map{|e| e.name} : [],
      dev_dependencies: dependencies && dependencies.development ? dependencies.development.map{|e| e.name} : [],
      version: version,
      versions: versions ? versions.map{|v| v.to_indexed} : []
    }.to_json
  end
  
  def self.simple_search(search_terms, options={})
    search = Tire.search RubyGem.tire.index.name, load:false do
      # What we're looking for
      query do
        string search_terms, fields: [:name, :info, :owners, :authors]
      end
      
      highlight :name, :info, :owners, :authors
      
      # Sort results
      sort { by :original_name }
      
      # Results pagination / number of results per page
      page = (options[:page] || 1).to_i
      search_size = options[:per] || DEFAULT_SEARCH_SIZE
      from (page -1) * search_size
      size search_size
      
      # Enable some facets
      if options[:facets]
        facet('global-licenses', :global => true) { terms :licenses, size: 6 }
        facet('current-licenses') { terms :licenses, size: 6 }
        facet('current-versions') { terms :version, size: 6 }
        facet('current-built_at', nested: 'versions') { date 'built_at', interval: 'month'}
      end
    end
  end
  
  def self.advanced_search(search_conditions, options={})
    fields = [:name, :info, :owners, :authors, :licenses, :version, :runtime_dependencies, :dev_dependencies]
    
    search = Tire.search RubyGem.tire.index.name, load:false do
      
      # What we're looking for
      query do
        boolean do
          fields.each do |field|
            must { string search_conditions[field], :default_operator => 'AND', :fields => [field] } if search_conditions[field].present?
          end
        end
      end
      
      highlight *fields
      
      # Sort results
      sort { by :original_name }
      
      # Results pagination / number of results per page
      page = (options[:page] || 1).to_i
      search_size = options[:per] || DEFAULT_SEARCH_SIZE
      from (page -1) * search_size
      size search_size
      
      # Enable some facets
      if search_conditions['facets']
        facet('global-licenses', :global => true) { terms :licenses, size: 6 }
        facet('current-licenses') { terms :licenses, size: 6 }
        facet('current-versions') { terms :version, size: 6 }
        facet('current-built_at', nested: 'versions') { date 'built_at', interval: 'month'}
      end
      
    end
  end
  
end

app/models/version.rb
class Version
  include Mongoid::Document

  field :authors, type: String
  field :built_at, type: String
  field :description, type: String
  field :downloads_count, type: Integer
  field :number, type: String
  field :summary, type: String
  field :platform, type: String
  field :prerelease, type: Boolean
  field :licenses, type: Array  #of strings

  embedded_in :ruby_gem

  def to_indexed
    {built_at: built_at.to_date, number: number, description: description, summary: summary}
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/gems_controller.rb
class GemsController < ApplicationController
  
  def index
    @gems = RubyGem.asc(:name).page(params[:page]).per(RubyGem::DEFAULT_SEARCH_SIZE)
  end
  
  def show
    @gem = RubyGem.find(params[:id])
  end
  
  def search
    redirect_to "/" and return unless params[:search].present? && params[:search][:q].present?
    
    search = RubyGem.simple_search(params[:search][:q], page: params[:page], facets: false)
    @gems = search.results
        
    render 'index'
  end
  
  def advanced_search
    params[:search] ||={}
    @show_advanced = true
    
    search = RubyGem.advanced_search(params[:search], page: params[:page])
    @gems = search.results
    
    render 'index'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/search_helper.rb
module SearchHelper

  def total_found(gems)
    (gems.respond_to? :total) ? "Found <em>#{gems.total}</em> results, showing <em>#{gems.count}</em>".html_safe : "Found <em>#{gems.count}</em> results.".html_safe
  end
  
  def replace_search_param(original_params, name, value)
    local_params = original_params.dup
    local_params[:search] ||= {}
    local_params[:search] = local_params[:search].dup
    local_params[:search][name] = value
    
    local_params
  end
  
  def original_search(params)
    params[:search] && params[:search][:q]
  end
  
end

app/views/gems/_advanced.html.haml
.panel-group#accordion
  .panel.panel-default
    .panel-heading
      .panel-title
        %h4
          %a{data:{toggle: "collapse", parent:"#accordion"}, href: "#collapseOne"} Advanced Search

    #collapseOne.panel-collapse.collapse.in
      .panel-body
      
        .well
          %form{role: "form", action: advanced_path, method: 'get'}
            .row
              .col-md-4
                .form-group
                  %label{for: "gem-name"} Name
                  %input#gem-name.form-control{placeholder: "Search in 'gem name'", type: "text", name: 'search[name]', value: params[:search][:name]}
        
              .col-md-4
                .form-group
                  %label{for: "gem-info"} Info
                  %input#gem-info.form-control{placeholder: "Search in 'info'", type: "text", name: 'search[info]', value: params[:search][:info]}

              .col-md-2
                .form-group
                  %label{for: "gem-license"} License
                  %input#gem-license.form-control{placeholder: "Search in 'licenses'", type: "text", name: 'search[licenses]', value: params[:search][:licenses]}

              .col-md-2
                .form-group
                  %label{for: "gem-dev-dependency"} Version
                  %input#gem-dev-dependency.form-control{placeholder: "Search in 'version'", type: "text", name: 'search[version]', value: params[:search][:version]}
    

            .row
  
              .col-md-6
                .form-group
                  %label{for: "gem-owners"} Owners
                  %input#gem-owners.form-control{placeholder: "Search in 'owners'", type: "text", name: 'search[owners]', value: params[:search][:owners]}

              .col-md-6
                .form-group
                  %label{for: "gem-authors"} Authors
                  %input#gem-authors.form-control{placeholder: "Search in 'authors'", type: "text", name: 'search[authors]', value: params[:search][:authors]}

            .row
              .col-md-6
                .form-group
                  %label{for: "gem-runtime-dependency"} Runtime dependencies
                  %input#gem-runtime-dependency.form-control{placeholder: "Search in 'runtime dependencies'", type: "text", name: 'search[runtime_dependencies]', value: params[:search][:runtime_dependencies]}

              .col-md-6
                .form-group
                  %label{for: "gem-dev-dependency"} Dev dependencies
                  %input#gem-dev-dependency.form-control{placeholder: "Search in 'dev dependencies'", type: "text", name: 'search[dev_dependencies]', value: params[:search][:dev_dependencies]}

            .row
              .col-md-6
                .checkbox
                  %label
                    %input{type: "checkbox", value: '1', name: 'search[facets]', checked: params[:search][:facets]}
                    Facets?
    
      
            %button.btn.btn-danger{type: "submit"} Submit

app/views/gems/_facet.html.haml
%li  
  = link_to "<b>#{facet['term']}</b> <span class='label label-success'>#{facet['count']}</span>".html_safe, replace_search_param(params, search_option, facet['term'])

app/views/gems/_facets.html.haml
.sidebar-nav
  .well
    %ul.nav.nav-list
      %li.nav-header 
        %i.icon.icon-file
        Licenses
      
      -@gems.facets['global-licenses']['terms'].each do |facet|
        =render partial: 'gems/facet', locals: {facet: facet, search_option:'licenses'}
            
      %li.nav-header 
        %i.icon.icon-file-alt
        Licenses
        %small (query)

      -@gems.facets['current-licenses']['terms'].each do |facet|
        =render partial: 'gems/facet', locals: {facet: facet, search_option:'licenses'}
      
      %li.nav-header 
        %i.icon-copy
        Versions
      
      -@gems.facets['current-versions']['terms'].each do |facet|
        =render partial: 'gems/facet', locals: {facet: facet, search_option:'version'}
      
      %li.nav-header 
        %i.icon-time
        Dates
      
      -@gems.facets['current-built_at']['entries'].reverse[0..5].each do |facet|
        %li
          %a          
            %b=Time.at(facet['time'] / 1000).strftime('%b %y')
            %span.label.label-success=facet['count']

app/views/gems/_highlight.html.haml
- %w(name info owners authors licenses version runtime_dependencies dev_dependencies).each do |field|
  -if highlight.send(field)
    %b #{field.capitalize}:
    =highlight.send(field).join(' ... ').html_safe
    %br

app/views/gems/_search.html.haml
=form_tag(search_path, id: 'new_search', class: 'navbar-form navbar-left', method: 'get') do
  .form-group
    %input.form-control{autofocus: "", placeholder: "Search gems...", type: "text", id: 'gems_search', name: 'search[q]', value: original_search(params)}
    
  %button.btn.btn-danger{type: "submit"}
    Search

app/views/gems/_serp.html.haml
%table.table.table-striped
  %tr
    %td.col-md-8 Name
    %td.col-md-1 Version
    %td Authors
  - @gems.each do |gem|
    %tr
      %td
        %b=link_to gem.name, gem_url(gem)
        
        -if gem.respond_to?(:highlight) && gem.highlight.present?
          %p.highlight
            =render partial:'gems/highlight', locals:{highlight: gem.highlight}
      %td
        =gem.version
      %td
        =gem.authors.is_a?(Array) ? gem.authors.join(', ') : gem.authors

app/views/gems/index.html.haml
.content
  .panel.panel-default
    .panel-body
      -if @show_advanced
        .row
          .col-md-12
            =render partial:'gems/advanced'
      .row
        .col-md-4.results
          =total_found(@gems)
      .row
        
        -if @gems.respond_to?(:facets) && @gems.facets.present?
          .col-md-2
            = render partial:'gems/facets'
          
        %div{class: (@gems.respond_to?(:facets) && @gems.facets.present? ? 'col-md-10' : 'col-md-12')}
          = render partial:'gems/serp'
        
          %tr
            %td{colspan: 2}
              = paginate @gems

app/views/gems/show.html.haml
.content
  .panel.panel-default
    .panel-body
      %table.table.table-striped
        %tr
          %td.col-md-2 
            %b Name
          %td=@gem.name

        %tr
          %td
            %b Version
          %td=@gem.version

        %tr
          %td
            %b Downloads 
          %td=@gem.downloads

        %tr
          %td
            %b Version Downloads
          %td=@gem.version_downloads

        %tr
          %td
            %b Platform
          %td=@gem.platform

        %tr
          %td 
            %b Authors
          %td=@gem.authors
          
        %tr
          %td
            %b Info
          %td=@gem.info
        
        %tr
          %td
            %b Licenses 
          %td=@gem.licenses.try(:join, ',')

        %tr
          %td
            %b Project url 
          %td=link_to @gem.project_uri, @gem.project_uri

        %tr
          %td
            %b Gem url 
          %td=link_to @gem.gem_uri, @gem.gem_uri
          
        %tr
          %td
            %b Homepage url 
          %td=link_to @gem.homepage_uri, @gem.homepage_uri

        %tr
          %td
            %b Wiki url 
          %td=link_to @gem.wiki_uri, @gem.wiki_uri
                            
        %tr
          %td
            %b Documentation url 
          %td=link_to @gem.documentation_uri, @gem.documentation_uri
  
        %tr
          %td
            %b Mailing list url 
          %td=link_to @gem.mailing_list_uri, @gem.mailing_list_uri
  
        %tr
          %td
            %b Source code url 
          %td=link_to @gem.source_code_uri, @gem.source_code_uri 

        %tr
          %td
            %b Bug tracker url 
          %td=link_to @gem.bug_tracker_uri, @gem.bug_tracker_uri

        %tr
          %td
            %b Owners
          %td
            -if @gem.owners
              =@gem.owners.map{|owner| owner.email }.join(', ')
      
      %table.table.table-striped
        %tr
          %th.col-md-2 Runtime Dependencies
          %th
        -@gem.dependencies.runtime.each do |runtime|
          %tr
            %td=runtime.name
            %td=runtime.requirements
            
      %table.table.table-striped
        %tr
          %th.col-md-2 Dev Dependencies
          %th
        -@gem.dependencies.development.each do |dev|
          %tr
            %td=dev.name
            %td=dev.requirements
            
      -if @gem.versions     
        -@gem.versions.each do |version|
          
          
          %table.table.table-striped
            %tr
              %td{colspan: 2}
                %b Version #{version.number}
            
            %tr 
              %td.col-md-3
                %b Built at:
              %td=version.built_at
          
            %tr
              %td 
                %b Number of downloads
              %td=version.downloads_count
              
            %tr
              %td 
                %b Description
              %td=version.description

            %tr
              %td 
                %b Summary
              %td=version.summary
              
            %tr
              %td 
                %b Platform
              %td=version.platform
              
            %tr
              %td 
                %b Prerelease
              %td=version.prerelease
              
            %tr
              %td 
                %b Licenses
              %td=version.licenses.try(:join, ', ')
          
            %tr
              %td 
                %b Authors
              %td=version.authors

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse{role: "navigation"}
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-ex8-collapse", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{href: '/'}
      RubyGems Search
  / Collect the nav links, forms, and other content for toggling
  .collapse.navbar-collapse.navbar-ex8-collapse
    %ul.nav.navbar-nav.navbar-right
      %li=link_to('Advanced', advanced_path)
      %li
        =render partial: 'gems/search'

app/views/layouts/application.html.haml
!!!
%html{lang:'en'}
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "RubyGems Search"
      %meta{name:"viewport", content:"width=device-width, initial-scale=1.0"}
      %meta{:content => content_for?(:description) ? yield(:description) : "RubyGems Search", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %section.container
      = render 'layouts/navigation'
      #main{:role => "main"}
        .container
          .content
            .row
              .span12
                = render 'layouts/messages'
                = yield
            %footer
              %hr
                RubyGems Search - © 2013
      / ! end of .container
    / ! end of #main


    =javascript_include_tag :application
    =yield :javascript_loaded
    :javascript
      $(function(){
        #{yield :page_javascript}
      });